### ISSUE TITLE
Two minor issues

### ISSUE THREAD

**Issue by e1ven** [mikeboers/PyTomCrypt#1]
Thanks for the lib!
You might want to change preprocess to use #!/usr/bin/env python rather than hardcoding a path.
Also, you're missing the .c files in the current git builds ;)

**Comment by mikeboers** [comment]
Good idea. I just pushed the preprocessor change.

To what C files do you refer? LibTomCrypt and LibTomMath are in lib directory, and the Python C modules are created by Mako and Cython. `make sources` to create them.

The build process needs lots of work, I'll admit, but it works just fine for distributing on the PyPI.

**Comment by e1ven** [comment]
Wow, you're online ;)

When I tried to compile with make sources, it complained that that it couldn't find _core.c

/usr/bin/cc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -O3 -w -pipe -DLTM_DESC -DLTC_SOURCE -I. -I./src -I./lib/libtomcrypt-1.17/src/headers -I./lib/libtommath-0.41 -I/usr/local/Cellar/python3/3.2.1/include/python3.2m -c tomcrypt/_core.c -o build/temp.macosx-10.4-x86_64-3.2/tomcrypt/_core.o
i686-apple-darwin11-llvm-gcc-4.2: tomcrypt/_core.c: No such file or directory
i686-apple-darwin11-llvm-gcc-4.2: no input files
error: command '/usr/bin/cc' failed with exit status 1

When I did a "ls", I only saw-
**init**.py  utils.py     

I fixed this by downloading the PyPi version, and cping the files-
Threepwood:PyTomCrypt-0.6.1 e1ven$ cp tomcrypt/*.c ../PyTomCrypt/tomcrypt/

I then had-

-rw-r--r--  1 e1ven  staff     572 Dec  8 20:54 **init**.py
-rw-r--r--  1 e1ven  staff   67917 Dec  8 21:05 _core.c
-rw-r--r--  1 e1ven  staff  349536 Dec  8 21:05 cipher.c
-rw-r--r--  1 e1ven  staff  258595 Dec  8 21:05 ecc.c
-rw-r--r--  1 e1ven  staff  303636 Dec  8 21:05 hash.c
-rw-r--r--  1 e1ven  staff  206365 Dec  8 21:05 mac.c
-rw-r--r--  1 e1ven  staff   91343 Dec  8 21:05 pkcs1.c
-rw-r--r--  1 e1ven  staff   93256 Dec  8 21:05 pkcs5.c
-rw-r--r--  1 e1ven  staff  190298 Dec  8 21:05 prng.c
-rw-r--r--  1 e1ven  staff  369884 Dec  8 21:05 rsa.c
-rw-r--r--  1 e1ven  staff    1473 Dec  8 20:54 utils.py

If you check the directory in Github, these files aren't in the current master-
https://github.com/mikeboers/PyTomCrypt/tree/master/tomcrypt

**Comment by mikeboers** [comment]
I guess my build setup is even worse than I thought. ;)

The reason I don't keep the C files in the repo is because they are two generations of auto-generation away from the "real" source.

`make sources` _should_ look like:

```
$ make sources
./preprocess src/_core.pyx > build/src/tomcrypt._core.pyx
./preprocess src/cipher.pyx > build/src/tomcrypt.cipher.pyx
./preprocess src/ecc.pyx > build/src/tomcrypt.ecc.pyx
<<< SNIP >>>
cython -o tomcrypt/_core.c.tmp build/src/tomcrypt._core.pyx
mv tomcrypt/_core.c.tmp tomcrypt/_core.c
cython -o tomcrypt/cipher.c.tmp build/src/tomcrypt.cipher.pyx
mv tomcrypt/cipher.c.tmp tomcrypt/cipher.c
cython -o tomcrypt/ecc.c.tmp build/src/tomcrypt.ecc.pyx
mv tomcrypt/ecc.c.tmp tomcrypt/ecc.c
<<< SNIP >>>
```

**Comment by e1ven** [comment]
Thanks!
