### ISSUE TITLE
Docs say rsa.sign can pad with OAEP?

### ISSUE THREAD

**Issue by parke** [mikeboers/PyTomCrypt#17]
The docs say that RSA can sign (and verify) using the OAEP padding scheme.

http://mikeboers.github.io/PyTomCrypt/rsa.html
padding (str) – One of 'none', 'v1.5', 'oaep', or 'pss'.

However, I believe OAEP is intended for encryption, not signing.  PSS is newer and "provably secure", whereas v1.5 is older and may be compatible with more RSA libraries.  For example, according to its man page, the command line openssl rsautl program can sign/verify with v1.5, but does not yet support PSS.

So I doubt that OAEP should be used for sigining.  And "none" should probably only be used if some other padding has been applied manually.

It might be nice to note this in the docs.

See also:
http://stackoverflow.com/questions/3313698/rsa-pkcs1-compliant-signature
http://www.emc.com/emc-plus/rsa-labs/standards-initiatives/what-is-oaep.htm
http://www.emc.com/emc-plus/rsa-labs/standards-initiatives/what-is-pss-pss-r.htm
pages 93-95 (105-107) of the libtom pdf documentation

**Comment by mikeboers** [comment]
You are correct. I believe this may have been some sloppy copying in the docstrings.

I don't think tomcrypt would let you encrypt with PSS anyways.

I'm looking into it.

**Comment by parke** [comment]
Also, the saltlen parameter is listed for rsa.sign and rsa.verify, but not explained.

Also verify has a "sign" parameter in one place and "sig" in another.

**Comment by mikeboers** [comment]
The libtom does reject invalid padding modes:

```
>>> from tomcrypt.rsa import Key
>>> k = Key(1024)
>>> k.encrypt('something', padding='pss')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tomcrypt.rsa.pyx", line 478, in tomcrypt.rsa.Key.encrypt (tomcrypt/rsa.c:4922)
  File "tomcrypt.rsa.pyx", line 499, in tomcrypt.rsa.Key.encrypt (tomcrypt/rsa.c:4774)
  File "tomcrypt._core.pyx", line 21, in tomcrypt._core.check_for_error (tomcrypt/_core.c:963)
tomcrypt.LibError: Invalid padding mode.
```

and

```
>>> k.sign('something', saltlen=0, padding='oaep')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tomcrypt.rsa.pyx", line 545, in tomcrypt.rsa.Key.sign (tomcrypt/rsa.c:5729)
  File "tomcrypt.rsa.pyx", line 568, in tomcrypt.rsa.Key.sign (tomcrypt/rsa.c:5571)
  File "tomcrypt._core.pyx", line 21, in tomcrypt._core.check_for_error (tomcrypt/_core.c:963)
tomcrypt.LibError: Invalid padding mode.
```

So that is a documentation fix, as you suggest.

**Comment by mikeboers** [comment]
I have fixed the docs for the padding modes, and `saltlen` parameter.

`sig` is short for "signature", not the act of "sign"ing. It still seems appropriate-ish.

**Comment by parke** [comment]
To clarify... from the docs:

verify(input, sign, hash='sha512', padding='pss', saltlen=None)

The second parameter should probably be "sig", not "sign".

**Comment by mikeboers** [comment]
I have made a better effort of explaining this in the docs.

**Comment by mikeboers** [comment]
Ah. I have fixed the typo.

Thanks for the clarification. =]
