### ISSUE TITLE
On cipher creation, does 'mode' really have to be a keyword argument?

### ISSUE THREAD

**Issue by parke** [mikeboers/PyTomCrypt#21]
Not a huge deal, but this could be a minor improvement to the cipher API.

```
import tomcrypt.cipher
key = iv = plaintext = b'0'*16

# The first line works, which is good.
# It seems reasonable to expect the second line to work, but it throws an exception.
ciphertext = tomcrypt.cipher.aes (key, iv, mode='ecb').encrypt (plaintext)
ciphertext = tomcrypt.cipher.aes (key, iv, 'ecb').encrypt (plaintext)
```

The exception is:

```
TypeError: __init__() got multiple values for keyword argument 'cipher'
```

**Comment by mikeboers** [comment]
Seems reasonable. I'll look into it.

## 

Mike Boers (on the road)

On 2013-09-09, at 10:15 AM, parke notifications@github.com wrote:

Not a huge deal, but this could be a minor improvement to the cipher API.

import tomcrypt.cipher
key = iv = plaintext = b'0'*16

# The first line works, which is good.

# It seems reasonable to expect the second line to work, but it throws

an exception.
ciphertext = tomcrypt.cipher.aes (key, iv, mode='ecb').encrypt (plaintext)
ciphertext = tomcrypt.cipher.aes (key, iv, 'ecb').encrypt (plaintext)

The exception is:

TypeError: **init**() got multiple values for keyword argument 'cipher'

—
Reply to this email directly or view it on
GitHubhttps://github.com/mikeboers/PyTomCrypt/issues/21
.

**Comment by parke** [comment]
Aside: I've just realized that ECB doesn't use an IV.  Which makes the above example look a little silly, but does not (IMO) invalidate the suggestion.

**Comment by mikeboers** [comment]
It makes me want to throw an exception  when a nonnull IV is provided to
avoid thinking it does anything.

## 

Mike Boers (on the road)

On 2013-09-09, at 10:24 AM, parke notifications@github.com wrote:

Aside: I've just realized that ECB doesn't use an IV. Which makes the above
example look a little silly, but does not (IMO) invalidate the suggestion.

—
Reply to this email directly or view it on
GitHubhttps://github.com/mikeboers/PyTomCrypt/issues/21#issuecomment-24097272
.

**Comment by parke** [comment]
An exception would be fine.  So the ECB-specific example would be adjusted to:

  ciphertext = tomcrypt.cipher.aes (key, None, mode='ecb').encrypt (plaintext)
  ciphertext = tomcrypt.cipher.aes (key, None, 'ecb').encrypt (plaintext)

**Comment by mikeboers** [comment]
Done, and in the `develop` branch.

**Comment by parke** [comment]
Have you updated the documentation?

Or maybe you want to wait until the next release?

**Comment by mikeboers** [comment]
Since I deploy my own docs (as opposed to using Read The Docs like I do on my other projects), I only have the one version deployed. Ergo, I don't want to deploy them until they correspond to the most up-to-date version on PyPI.

However, I didn't do a good enough job documenting this, and I'm considering another small change.

We now have:

```
x = tomcrypt.cipher.aes(key, iv, mode)
```

AND

```
x = tomcrypt.cipher.Cipher(key, iv, cipher, mode)
```

I feel as if these are no longer in sync, but I don't really want to introduce the backwards incompatible change.

**Comment by mikeboers** [comment]
I have made the use of IVs more explicit. `None` does not turn into an implicit NULL IV anymore.

I have made the API difference between `tomcrypt.cipher.Descriptor.__call__` and `tomcrypt.cipher.Cipher` more explicit, so my other concern is no longer strong.

**Comment by mikeboers** [comment]
Version 0.8.0 is out, along with new docs.
