### ISSUE TITLE
Expose tomcrypt module version?

### ISSUE THREAD

**Issue by parke** [mikeboers/PyTomCrypt#26]
Is there an easy way for me to determine (at runtime) which version of PyTomCrypt I have installed?

Something like: tomcrypt.version_info ?

**Comment by mikeboers** [comment]
Nope! I'll add it.

I'm going to have a crazy week, so I'm not sure if I'll be able to do it
before the 25th.

## 

Mike Boers (on the road)

On Nov 18, 2013, at 11:39 AM, parke notifications@github.com wrote:

Is there an easy way for me to determine (at runtime) which version of
PyTomCrypt I have installed?

Something like: tomcrypt.version_info ?

—
Reply to this email directly or view it on
GitHubhttps://github.com/mikeboers/PyTomCrypt/issues/26
.

**Comment by mikeboers** [comment]
Done, and released as v0.10.1.

Check `tomcrypt.__version__`.

Cheers!

**Comment by parke** [comment]
Thanks!
